### ISSUE TITLE
How about half keys?

### ISSUE THREAD

**Issue by LovelyA72** [fynv/ScoreDraft#12]
I am wondering if there's any way to do half keys(black keys on the keyboard) in scoredraft. Based on my reading of the documentation, I can not yet find a way to do it.

**Comment by fynv** [comment]
In ScoreDraft.Notes, all 12 keys are defined as a list
Freqs=[2.0**(v/12.0) for v in range(12)]
, and you can find functions like 

def note(octave, freq, duration):
	return (freq*(2.0**(octave-5.0)), duration)

def do(octave=5, duration=48):
	return note(octave,Freqs[0],duration)

def set_do(freq):
	Freqs[0]=freq

That's how notes are defined. To define the half keys, you can just add your own functions like do()

Here's an [example](https://github.com/fynv/ScoreDraft/blob/master/python_test/NaushikaRequiem.py):

import ScoreDraft
from ScoreDraft.Notes import *

def soS(octave=5, duration=48):
	return (Freqs[8]*(2.0**(octave-5.0)), duration)

def set_soS(freq):
	Freqs[8]=freq

or, soS() can simply be:

def soS(octave=5, duration=48):
	return note(octave,Freqs[8],duration)

**Comment by LovelyA72** [comment]
Thanks for the fast reply! Will try it tonight. It can be better if the system pre-define them though~
