### ISSUE TITLE
运行python_test下的任何Python脚本，提示分段错误

### ISSUE THREAD

**Issue by Icemap** [fynv/ScoreDraft#14]
平台：MacOS v10.14.6
过程：
1. 关闭CUDA支持
2. 删除QT依赖模块
3. CMakeLists.txt指定build路径，指定python_test路径
4. cmake ./
5. make
6. make install
7. 运行脚本报错

~~~
/usr/local/bin/python3.7 /Users/cheese/Src/PythonSrc/ScoreDraft/python_test/piano_test.py

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
~~~

**Comment by fynv** [comment]
最近的更新后似乎还没有在MacOS下测过，我回头试一下

**Comment by Icemap** [comment]
好的，麻烦您了。

**Comment by fynv** [comment]
Win10 升级以后老的VM在VMWare Player里运行不了。看来得花点时间了。

**Comment by fynv** [comment]
我这篇测了下piano_test.py，在MacOS v10.13测试没有问题，生成了piano_test.wav.
估计可能的问题：
1. 脚本要在python_test，或者你指定的其他安装路径下运行，这样用相对路径就可以：
python_test user$ /usr/local/bin/python3.7 piano_test.py
2. 确认python_test/ScoreDraft/InstrumentSample 目录存在，没有的话去自带的python_test目录里找到拷过来

**Comment by Icemap** [comment]
好的。麻烦了。我再测试一下。
