### ISSUE TITLE
Cannot compile on macOS

### ISSUE THREAD

**Issue by Jobsecond** [fynv/ScoreDraft#3]
I tried to use CMake GUI (3.11.0) to configure the project, but it shows error `CUDA_SDK_ROOT_DIR-NOTFOUND`. CUDA Toolkit 9.1 is already installed.

<img width="667" alt="CMake errors" src="https://user-images.githubusercontent.com/25559254/38515425-143103c6-3be9-11e8-8bc0-a5133bbf8367.png">

**Model:** MacBook Pro (Retina, 15-inch, Mid 2015)
**Processor:** Intel Core i7-4870HQ @ 2.50GHz
**Graphics:** AMD Radeon R9 M370X 2048 MB / Intel Iris Pro 1536 MB
**Memory:** 16 GB 1600 MHz DDR3
**OS:** macOS 10.13.4 (17E199)

**Comment by Jobsecond** [comment]
I have disabled `QtPCMPlayer` and `Meteor` in `CMakeLists.txt`.

**Comment by fynv** [comment]
Hi Jobsecond, sorry that I don't have macOS, and have never tried with it.
For the specific issue, I suggest you open UtauDraft/CMakeLists.txt, change:
`set (USE_CUDA true)`
to 
`set (USE_CUDA false)`
and re-cmake.

Because you don't have NV GPU, so using CUDA doesn't make sense. (I should say something about it in "About building"). Actually, the speed-up is not great even when CUDA is available. 
There are bound to be other issues on macOS. So don't close the issue yet, and let see what comes next.

Thanks.

**Comment by Jobsecond** [comment]
Thanks for your reply. I changed `USE_CUDA` to `false`, and it no longer requires CUDA. However, when I try to compile, it says `error: use of undeclared identifier`. (I enabled all modules in `CMakeLists.txt`)

```
Scanning dependencies of target QtPCMPlayer
[ 48%] Building CXX object QtPCMPlayer/CMakeFiles/QtPCMPlayer.dir/main.cpp.o
[ 50%] Building CXX object QtPCMPlayer/CMakeFiles/QtPCMPlayer.dir/QtPCMPlayer.cpp.o
[ 51%] Building CXX object QtPCMPlayer/CMakeFiles/QtPCMPlayer.dir/ViewWidget.cpp.o
/Users/kevin/Documents/GitHub/ScoreDraft/QtPCMPlayer/ViewWidget.cpp:58:23: error: use of undeclared identifier 'cosf'
                                float win = 0.5f*(cosf(x*(float)PI) + 1.0f);
                                                  ^
/Users/kevin/Documents/GitHub/ScoreDraft/QtPCMPlayer/ViewWidget.cpp:69:20: error: use of undeclared identifier 'powf'
                                float fstart = powf(2.0f, (float)i*0.1f);
                                               ^
/Users/kevin/Documents/GitHub/ScoreDraft/QtPCMPlayer/ViewWidget.cpp:70:19: error: use of undeclared identifier 'powf'
                                float fstop = powf(2.0f, (float)(i + 1)*0.1f);
                                              ^
/Users/kevin/Documents/GitHub/ScoreDraft/QtPCMPlayer/ViewWidget.cpp:72:33: error: use of undeclared identifier 'ceilf'
                                unsigned ustart = (unsigned)ceilf(fstart);
                                                            ^
/Users/kevin/Documents/GitHub/ScoreDraft/QtPCMPlayer/ViewWidget.cpp:73:32: error: use of undeclared identifier 'ceilf'
                                unsigned ustop = (unsigned)ceilf(fstop);
                                                           ^
/Users/kevin/Documents/GitHub/ScoreDraft/QtPCMPlayer/ViewWidget.cpp:87:15: error: use of undeclared identifier 'logf'
                                barv[i] = logf(ave*10.0f) / 10.0f;
                                          ^
6 errors generated.
make[2]: *** [QtPCMPlayer/CMakeFiles/QtPCMPlayer.dir/ViewWidget.cpp.o] Error 1
make[1]: *** [QtPCMPlayer/CMakeFiles/QtPCMPlayer.dir/all] Error 2
make: *** [all] Error 2
```

When I remove `QtPCMPlayer` module from `CMakeLists.txt` (with other modules enabled), there are no errors.

Here is my compiler version:
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Qt version:
```
$ qmake -v
QMake version 3.1
Using Qt version 5.10.1 in /Users/Shared/Qt/5.10.1/clang_64/lib
```

**Comment by Jobsecond** [comment]
`undeclared identifier` error also occurs when building `QtPCMPlayer` on my linux server Fedora 26 (using gcc version 7.3.1).

**Comment by fynv** [comment]
If pushed a fix to ViewWidget.cpp, please try if the issue is fixed.
Thanks.

**Comment by fynv** [comment]
Sorry, fixed wrong location in the first commit. You can try it now.

**Comment by Jobsecond** [comment]
OK, the error is solved. Successfully built.

**Comment by fynv** [comment]
Great to hear that. I was expecting more issues in macOS..

**Comment by Jobsecond** [comment]
I will keep testing on macOS.
