### ISSUE TITLE
Crashes on macOS

### ISSUE THREAD

**Issue by Jobsecond** [fynv/ScoreDraft#4]
When running the program, the wav file is successfully mixed down and sounds correctly, but then python crashes.

Here is my program:
`Hello.py` (located in the same directory as `ScoreDraft.py`):
```python
import sys

import ScoreDraft
from ScoreDraftNotes import *

doc=ScoreDraft.Document()

seq=[do(),do(),so(),so(),la(),la(),so(5,96)]

doc.playNoteSeq(seq, ScoreDraft.Triangle())
doc.mixDown('Hello.wav')
```
Here is the shell output:
```
$ /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 Hello.py 
Loading extension: libPercussionSampler.so
Loading extension: libUtauDraft.so
Loading extension: libInstrumentSampler.so
Loading extension: libMIDIWriter.so
Loading extension: libKeLa.so
Illegal instruction: 4
```
Attached is the error report: [ErrorReport_ScoreDraft.txt](https://github.com/fynv/ScoreDraft/files/1895838/ErrorReport_ScoreDraft.txt)

**Comment by fynv** [comment]
I see nothing obviously wrong with InstrumentSamplerInitializer. I'll setup a macOS in virtual machine and try it myself.

**Comment by fynv** [comment]
In macOS, I see some hint from the compile warnings, which I think can lead to a fix to the crash issue.
Before fixing it, could you tell me how you dealt with the extensions difference of shared libraries? (default is ".dylib" instead of ".so")

**Comment by Jobsecond** [comment]
I use `.so` extension instead of `.dylib` because Python does not recognize `.dylib`.

**Comment by Jobsecond** [comment]
I'd like to add some details that when using `Piano`, whether it crashes depends on the PITCH of notes.

Here are my tests for `Piano` instrument:
1. For a note sequence `seq = [(4.0, 48)]` it CRASHES. Any pitches >= 4.0 will also cause it to crash.
2. For a note sequence `seq = [(2.0, 48)]`, it works fine. Any pitches < 4.0 also works fine.

Maybe the information about `Piano` sampler instrument is helpful:
```console
$ ls
Alesis-Fusion-Bright-Acoustic-Piano-C2.freq
Alesis-Fusion-Bright-Acoustic-Piano-C2.wav
Alesis-Fusion-Bright-Acoustic-Piano-C4.freq
Alesis-Fusion-Bright-Acoustic-Piano-C4.wav
Alesis-Fusion-Bright-Acoustic-Piano-C6.freq
Alesis-Fusion-Bright-Acoustic-Piano-C6.wav
$ cat Alesis-Fusion-Bright-Acoustic-Piano-C2.freq
66.0
$ cat Alesis-Fusion-Bright-Acoustic-Piano-C4.freq
264.0
$ cat Alesis-Fusion-Bright-Acoustic-Piano-C6.freq
1056.0
```

**Comment by fynv** [comment]
Yes, this one is a bug independent of platform. I just fixed it. (Binary for windows not updated yet. Need recompile for both platforms).

**Comment by fynv** [comment]
Did some more fixes (missing virtual destructors for base classes is worse than I thought).
Also updated binaries for Win/Linux

**Comment by fynv** [comment]
I tried Qt in macOS just now. ScoreDraft has some deployment issue with Qt, so related modules are not working. And I don't think I can fix it. some modules hits the issue as discussed in:
https://stackoverflow.com/questions/11054087/starting-qt-gui-from-dll-in-dllstart-function

**Comment by fynv** [comment]
Closing
