### ISSUE TITLE
Fail to build on Android 无法在 Android 上编译(aarch64)

### ISSUE THREAD

**Issue by ZeroAurora** [fynv/ScoreDraft#8]
编译平台：Android aarch64（使用 Termux）

版本：
- ScoreDraft 源码：最新 master
- cmake：3.11.1
- make：4.2.1
- clang：6.0.0
- python：3.6.5

错误回显：

```
[ 26%] Built target ScoreDraftCore
[ 34%] Built target WavUtil
[ 36%] Building CXX object PyScoreDraft/CMakeFiles/PyScoreDraft.dir/PyScoreDraft.cpp.o
In file included from /data/data/com.termux/files/home/ScoreDraft/PyScoreDraft/PyScoreDraft.cpp:1:
/data/data/com.termux/files/usr/include/python3.6m/Python.h:39:10: fatal error:
      'crypt.h' file not found
#include <crypt.h>
         ^~~~~~~~~
1 error generated.
make[2]: *** [PyScoreDraft/CMakeFiles/PyScoreDraft.dir/build.make:63: PyScoreDraft/CMakeFiles/PyScoreDraft.dir/PyScoreDraft.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:197: PyScoreDraft/CMakeFiles/PyScoreDraft.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by fynv** [comment]
Hi! Frankly, I've never thought about compiling ScoreDraft on Android, since it needs Python to work.
Could you tell me what is the point to use Python on Android? IMO the development environment on Android sucks! Even if I do want to try compiling for Android, I will consider some cross-compiling tools instead of compiling on Android directly. (Termux works on Android directly right?)

简单说，能告诉我你在安卓上编译 ScoreDraft 是想达到什么样的效果吗？

**Comment by ZeroAurora** [comment]
在安卓编译的主要目的是平时没有开发工具。。。
希望使用去除 Qt 和 CUDA 模块后的功能，或者说可以正常使用所有的生成功能。
（错误原因貌似是 Termux 割了模块，详细有待观察）

**Comment by fynv** [comment]
我先在X86机器上用RemixOS试试。话说你用的难道也是有键盘的安卓设备？要不怎么码Python代码？

**Comment by ZeroAurora** [comment]
可以用虚拟键盘的(・・;)
![Screenshot_20180513-124735-307.jpg](https://i.loli.net/2018/05/13/5af7c3841b1d5.jpg)

**Comment by fynv** [comment]
我这边尝试用Remix编译，似乎不行，最简单的程序也编译不过。
手头也没有其他适合折腾的安卓设备了。
真心不建议在安卓上搞开发，哪怕用树莓派呢。。

**Comment by fynv** [comment]
您好，我最近开了新项目SingingGadgets，支持Setuptools编译，语音合成功能与ScoreDraft基本一致。您可以尝试下载GitHub.com/fynv/SingingGadgets代码，然后运行python3 setup.py build 编译，看看能不能行得通。SingingGadgets相比起ScoreDraft，C++的成分缩减了很多。

**Comment by ZeroAurora** [comment]
RPi 3B+ 已到手~SingingGadgets 以后会试的
